# CMSSW runtime environment (replaces `cmsenv` for the conda installation)
export CMSSW_CONDA_BACKUP_SCRAM_ARCH="${SCRAM_ARCH:-}"
export CMSSW_CONDA_BACKUP_ROOT_INCLUDE_PATH="${ROOT_INCLUDE_PATH:-}"
export CMSSW_CONDA_BACKUP_ROOT_LIBRARY_PATH="${ROOT_LIBRARY_PATH:-}"

export SCRAM_ARCH=@SCRAM_ARCH@
export CMSSW_VERSION=@CMSSW_VERSION@
export CMSSW_BASE="${CONDA_PREFIX}/share/cmssw/@SCRAM_ARCH@/cms/cmssw/@CMSSW_VERSION@"
export CMSSW_RELEASE_BASE=""
export LOCALRT="${CMSSW_BASE}"
export CMSSW_SEARCH_PATH="${CMSSW_BASE}/src"
export CMSSW_PLUGIN_PATH="${CMSSW_BASE}/lib/@SCRAM_ARCH@"
export ROOT_INCLUDE_PATH="${CMSSW_BASE}/src:${CONDA_PREFIX}/include/eigen3${ROOT_INCLUDE_PATH:+:${ROOT_INCLUDE_PATH}}"
export ROOT_LIBRARY_PATH="${CMSSW_BASE}/lib/@SCRAM_ARCH@${ROOT_LIBRARY_PATH:+:${ROOT_LIBRARY_PATH}}"
