if [ -n "${CONDA_BACKUP_CSC_TRACK_FINDER_DATA_DIR+x}" ]; then
  export CSC_TRACK_FINDER_DATA_DIR="${CONDA_BACKUP_CSC_TRACK_FINDER_DATA_DIR}"
  unset CONDA_BACKUP_CSC_TRACK_FINDER_DATA_DIR
else
  unset CSC_TRACK_FINDER_DATA_DIR
fi
